---
#
# Ansible managed
#
repository:
  description: Installs and configures adguardhome container based on official adguardhome docker container
  homepage: https://mullholland.net
  topics: cloud, development, webserver, adguardhome, proxy, ansible, molecule, tox, playbook
