---
- name: "adguardhome | Ensure app folders exists"
  ansible.builtin.file:
    name: '{{ adguardhome_docker_base_path }}/adguardhome/{{ item }}'
    owner: "{{ adguardhome_docker_user }}"
    group: "{{ adguardhome_docker_group }}"
    mode: "0770"
    state: directory
  with_items:
    - "conf"
    - "work"

- name: adguardhome | Get docker executable path
  ansible.builtin.command:
    cmd: "which docker"
  changed_when: false
  register: adguardhome_docker_executable_path

- name: "adguardhome | Create docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ adguardhome_docker_base_path }}/adguardhome/docker-compose.yml"
    mode: "0640"
    owner: "{{ adguardhome_docker_user }}"
    group: "{{ adguardhome_docker_group }}"
  notify: Adguardhome_restart

- name: "adguardhome | Create systemd service"
  ansible.builtin.template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/adguardhome.service"
    mode: "0770"
    owner: "root"
    group: "root"
  notify:
    - Adguardhome_systemd_reload
    - Adguardhome_restart
